safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "ChenDaqian"
description: '.NET Egineer<br/>ğŸ”­ Iâ€™m now working for <a href="https://www.beisen.com/" title="Beisen">Beisen</a>.<br/>ğŸ˜„ currently coding in <a href="https://learn.microsoft.com/en-us/dotnet/csharp/" title="CSharp">C#</a> and <a href="https://www.java.com/en/" title="Java">Java</a>.<br/>ğŸ’ I like playing <a href="https://www.xbox.com/en-us/games/store/dark-souls-remastered/BS18VCF4NLQ9/0001" title="DarkSouls">DarkSouls</a> and <a href="https://specialized.com.cn/?lang=en" title="specialized">Road cycling</a>.<br/>â“ Be free to ask me about anything <a href="https://github.com/ChenDaqian/ChenDaqian/issues" title="issues">here</a>.'
baseurl: "/"
url: "https://chendaqian.github.io/" # replace by your site's url
twitter_username: ChenDaqian
github_username:  ChenDaqian # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "ChenDaqian"
address: "Beijing, China"
email: "hi.world@outlook.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: zh

# exclude files
exclude:
  - LICENSE
  - README.md
