safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "ChenDaqian info"
description: ".NET engineer<br/>dddddd<br/>"
baseurl: "/"
url: "https://chendaqian.github.io/" # replace by your site's url
twitter_username: ChenDaqian
github_username:  ChenDaqian # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "ChenDaqian"
address: "haidianï¼ŒBeijing"
email: "hi.world@outlook.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: zh

# exclude files
exclude:
  - LICENSE
  - README.md
